### ISSUE TITLE
not working in safari 13.0.4 

### ISSUE THREAD

**Issue by sachin-blinkdigital** [Maykonn/js-detect-incognito-private-browsing#14]
works in older browser than 10.0 but not in safari 13.0.4

**Comment by Maykonn** [comment]
@sachin-blinkdigital thanks. Unfortunately, I'm not able to test with the mentioned version at the moment. Feel free to add any code update which works properly as a new Pull Request to be discussed further. As far I as know, it is not possible to easily detect (if it is possible to be done) the incognito browsing on newer Safari versions.

**Comment by monstermac77** [comment]
Any update on this? We actually are trying to reliably detect incognito mode in order to protect user's privacy by respecting their request not to be tracked: https://www.coursicle.com/blog/loginless-a-new-standard-for-user-identification.php
